name: Find Shorter Candidates

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *' #once a month

jobs:
  find-shorter-candidates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify your required Python version

      - name: Run find-num.py
        id: find_num
        run: |
          python find-num.py --range 255 > result.txt
          echo "::set-output name=result::$(cat result.txt)"

      - name: Check for new candidates and existing combinations
        id: check_candidates
        run: |
          NEW_CANDIDATES_FOUND=false
          while IFS= read -r line; do
            if [[ "$line" == *"(Existing)"* ]]; then
              echo "$line" >> existing_combinations.txt
            elif [[ "$line" == *","* ]]; then
              NEW_CANDIDATES_FOUND=true
            fi
          done < result.txt

          if [ "$NEW_CANDIDATES_FOUND" = true ]; then
            echo "::set-output name=new_candidates::true"
          else
            echo "::set-output name=new_candidates::false"
          fi

      - name: Create Pull Request for New Candidates
        if: steps.check_candidates.outputs.new_candidates == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Add new shorter candidates"
          body: "This PR adds new shorter candidates found by find-num.py."
          base: main
          branch: add-shorter-candidates-branch

      - name: Upload Existing Combinations Log
        if: steps.check_candidates.outputs.new_candidates == 'false'
        uses: actions/upload-artifact@v3
        with:
          name: existing-combinations-log
          path: existing_combinations.txt

